---
- name: "Log Repository: Elasticsearch"
  hosts: elasticsearch
  serial: 3
  become: true
  tasks:
    - name: Elasticsearch Deployment
      ansible.builtin.include_role:
        name: elasticsearch8 
      tags:
        - elasticsearch

- name: "Log Repository: Kibana"
  hosts: kibana
  serial: 3
  become: true
  tasks:
    - name: Kibana Deployment
      ansible.builtin.include_role:
        name: kibana8
      tags:
        - kibana

- name: "Log Repository: HAProxy"
  hosts: gateway
  serial: 3
  become: true
  tasks:
    - name: HAProxy Deployment
      ansible.builtin.include_role:
        name: haproxy
      tags:
        - haproxy

- name: "Log Repository: Keepalived"
  hosts: gateway
  serial: 3
  become: true 
  tasks:
    - name: Keepalived Deployment
      ansible.builtin.include_role:
        name: keepalived
      tags:
        - keepalived

- name: "Log Repository: Vector"
  hosts: gateway
  serial: 3
  become: true 
  tasks:
    - name: Vector Deployment
      ansible.builtin.include_role:
        name: vector
      tags:
        - vector
