---
- name: "Create directory to store vector packages"
  ansible.builtin.file:
    name: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ vector_target_package_path }}"
  tags:
    - ubuntu
    - vector

- name: "Copy Vector package to the target machine"
  ansible.builtin.copy:
    src: "{{ vector_package_path }}"
    dest: "{{ vector_target_package_path }}/vector-{{ vector_version }}-amd64.deb"
    mode: "0750"
  tags:
    - ubuntu
    - vector

- name: Install Vector Package
  ansible.builtin.apt:
    deb: "{{ vector_target_package_path }}/vector-{{ vector_version }}-amd64.deb"
    state: present
    install_recommends: false
  tags:
    - ubuntu
    - vector

- name: Create a custom configuration directory for vector
  ansible.builtin.file:
    name: "/etc/vector/config.d/"
    state: directory
    mode: "0755"
    owner: vector
    group: root
  tags:
    - ubuntu
    - vector

- name: Copy barebone config for vector's main config
  ansible.builtin.template:
    src: vector.yaml.j2
    dest: "/etc/vector/vector.yaml"
    mode: "0755"
    owner: vector
    group: root
  tags:
    - ubuntu
    - vector

- name: Copy custom configurations for vector
  tags:
    - ubuntu
    - vector
  block:
    - name: Find custom configurations
      delegate_to: localhost
      ansible.builtin.find:
        paths: "{{ vector_config_path }}"
        recurse: true
        patterns: "*.yaml"
      register: custom_vector_configurations

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ custom_vector_configurations }}"

    - name: Copy custom configurations
      ansible.builtin.template:
        src: "{{ item.path }}"
        dest: "/etc/vector/config.d/"
        mode: "0755"
        owner: vector
        group: root
      with_items:
        - "{{ custom_vector_configurations.files }}"
      when: custom_vector_configurations.matched > 0

- name: Modify Systemd unit file
  ansible.builtin.lineinfile:
    path: "/lib/systemd/system/vector.service"
    regex: "^ExecStart="
    line: ExecStart=/usr/bin/vector -w --config /etc/vector/vector.yaml
    mode: "0644"
  when: custom_vector_configurations.matched == 0

- name: Modify Systemd unit file
  ansible.builtin.lineinfile:
    path: "/lib/systemd/system/vector.service"
    regex: "^ExecStart="
    line: ExecStart=/usr/bin/vector -w --config /etc/vector/vector.yaml --config /etc/vector/config.d/*.yaml
    mode: "0644"
  when: custom_vector_configurations.matched > 0

- name: Start Vector Service
  ansible.builtin.systemd_service:
    name: vector
    state: restarted
    enabled: true
    daemon_reload: true
  tags:
    - ubuntu
    - vector
